<a href="https://colab.research.google.com/github/Tatoloops/PublicRepository/blob/PyNotebook/Python/Notebooks/Solemne_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solemne III

* Integrantes:  
> Tomás Castillo Á  
> Carlos Campos  
> Sebastián Gonzáles

##Procesamiento de Datos:

el conjunto de datos seleccionado está relacionado con el gasto anual de clientes en diferentes categorías de productos.

In [52]:
from google.colab import files

dataUpload = files.upload()

for fn in dataUpload.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(dataUpload[fn])))

Saving WholesaleCustomersData.xlsx to WholesaleCustomersData (1).xlsx
User uploaded file "WholesaleCustomersData (1).xlsx" with length 23595 bytes


In [53]:
import pandas as pd

dataFrame = pd.read_excel(next(iter(dataUpload.keys())))

Dentro del Dataframe hay información correspondiente a 3 regiones y 2 canales, se procederá a:
* Eliminar toda la información del canal 2.
* Eliminar toda la información de la región 3.
* Eliminar la columna "Channel" correspondiente a los canales (ya que toda la información restante pertenecerá al canal 1)  

Con esto sólo existirán los gastos anuales correspondientes a las categorías de productos para las regiones 1 y 2 sobre el mismo canal.

In [61]:
def delete_column(dataframe, column_name):
    if column_name in dataframe.columns:
        dataframe = dataframe.drop(column_name, axis=1)
        print(f"Column '{column_name}' deleted successfully.")
    else:
        print(f"Column '{column_name}' not found in the DataFrame.")

    return dataframe

def delete_rows(dataframe,name,value):
    if name in dataframe.columns:
        rows_to_delete = dataframe[dataframe[name] == value].index
        dataframe = dataframe.drop(index=rows_to_delete)
        print(f"Rows with '{name}' value equal to {value} deleted successfully.")
    else:
        print(f"Column '{name}' not found in the DataFrame.")

    return dataframe

dataFrame = delete_rows(dataFrame,"Channel",2)
dataFrame = delete_rows(dataFrame,"Region",3)
dataFrame = delete_column(dataFrame,"Channel")
dataFrame = delete_column(dataFrame,"Fresh")
dataFrame = delete_column(dataFrame,"Detergents_Paper")
dataFrame = delete_column(dataFrame,"Delicassen")

Column 'Channel' not found in the DataFrame.
Rows with 'Region' value equal to 3 deleted successfully.
Column 'Channel' not found in the DataFrame.
Column 'Fresh' deleted successfully.
Column 'Detergents_Paper' deleted successfully.
Column 'Delicassen' deleted successfully.


Agregamos una columna nueva a nuestro dataFrame llamada "year", la cual asignará un año a cada fila de nuestro dataset. Este proceso se realizará por cada región de nuestro estudio (1 y 2)

In [62]:

# Assuming your DataFrame is named dataFrame

# Create counters for each region
yearRegion1 = 1
yearRegion2 = 1

# Create an empty list to store the year values
years = []

# Loop through each row in the DataFrame
for index, row in dataFrame.iterrows():
    # Check the region of the current row
    if row['Region'] == 1:
        # Assign the year value based on the region counter
        years.append(yearRegion1)
        # Increment the counter for Region 1
        yearRegion1 += 1
    elif row['Region'] == 2:
        # Assign the year value based on the region counter
        years.append(yearRegion2)
        # Increment the counter for Region 2
        yearRegion2 += 1

# Add the "year" column to the DataFrame
dataFrame['year'] = years

# Display the updated DataFrame
print(dataFrame)


     Region   Milk  Grocery  Frozen  year
196       1   7209     4897   18711     1
198       1   2154     6824    3527     2
199       1   2280     2112     520     3
202       1  11487     9490    5065     4
203       1    685     2216     469     5
..      ...    ...      ...     ...   ...
332       2   3216     1447    2208    24
336       2   1511     1330     650    25
337       2   1347     2611    8170    26
338       2    333     7021   15601    27
339       2   1188     5332    9584    28

[87 rows x 5 columns]


In [66]:
def delete_column(dataframe, column_name):
    if column_name in dataframe.columns:
        dataframe = dataframe.drop(column_name, axis=1)
        print(f"Column '{column_name}' deleted successfully.")
    else:
        print(f"Column '{column_name}' not found in the DataFrame.")

    return dataframe

# Create two separate DataFrames based on the region
dataRegion1 = dataFrame[dataFrame['Region'] == 1]
dataRegion2 = dataFrame[dataFrame['Region'] == 2]

dataRegion1= delete_column(dataRegion1, "Region")
dataRegion2= delete_column(dataRegion2, "Region")
# Display the two DataFrames
print("Data for Region 1:")
print(dataRegion1)

print("\nData for Region 2:")
print(dataRegion2)

Column 'Region' deleted successfully.
Column 'Region' deleted successfully.
Data for Region 1:
      Milk  Grocery  Frozen  year
196   7209     4897   18711     1
198   2154     6824    3527     2
199   2280     2112     520     3
202  11487     9490    5065     4
203    685     2216     469     5
204    891     5226    1383     6
206    780      950     878     7
208   3748     5838    1859     8
210   1895     1393    1801     9
212   1012     2062    1291    10
213   6602     6861    1329    11
215  10765    15538    1374    12
217   1475     2046    2532    13
219    367     1390    2306    14
220    899     1382    1765    15
221   7503    10646      91    16
222   1115     2856    7496    17
224    659     1499     784    18
225   3243     4157     660    19
227   2204     1563    2286    20
228    577      572     950    21
229   2746     2501    6845    22
231  10678     3828    1439    23
232   1780     3838     638    24
233   4984     3316     937    25
234   2703     3833  

Para descargar los nuevos conjuntos de datos

In [67]:
dataRegion1.to_csv('dataRegion1.csv', index=False)
files.download('dataRegion1.csv')

dataRegion2.to_csv('dataRegion2.csv', index=False)
files.download('dataRegion2.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## Entrenando modelo para futuras predicciones:

Entrenamos nuestro primer modelo para predecir futuros gastos sobre cada región de consumo:

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

* Entrenando modelo para predecir gastos en los próximos años sobre cada región:

In [94]:
def Predictions(data,num):
    # X serán las características de entrada (region, categorías de productos), y será el gasto anual.
    X = data[['Milk', 'Grocery', 'Frozen']]
    y_columns = ['Milk', 'Grocery', 'Frozen']

    # Normalizar los datos
    scaler = StandardScaler()
    X_normalized = scaler.fit_transform(X)

    # Convertir datos a tensores de PyTorch
    X_tensor = torch.tensor(X_normalized, dtype=torch.float32)
    y_tensor = torch.tensor(data[y_columns].values, dtype=torch.float32)

    # División de datos
    X_train_tensor, X_test_tensor, y_train_tensor, y_test_tensor = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=42)

    # Definir la arquitectura de la red neuronal
    class ExpenditurePredictionModel(nn.Module):
        def __init__(self, input_size, output_size):
            super(ExpenditurePredictionModel, self).__init__()
            self.fc = nn.Linear(input_size, output_size)

        def forward(self, x):
            return self.fc(x)

    # Definir la función de pérdida y el optimizador
    criterion = nn.MSELoss()

    # Entrenamiento del modelo
    model = ExpenditurePredictionModel(X_train_tensor.shape[1], len(y_columns))
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    epochs = 500
    for epoch in range(epochs):
        optimizer.zero_grad()
        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)
        loss.backward()
        optimizer.step()

    # Evaluación del modelo en datos de prueba
    model.eval()
    with torch.no_grad():
        y_pred_tensor = model(X_test_tensor)

    # Predicción para las siguientes 5 filas
    with torch.no_grad():
        future_data = X_test_tensor[:5]
        future_predictions = model(future_data)

    # Convertir los tensores de PyTorch a numpy arrays
    y_pred_numpy = y_pred_tensor.numpy()
    future_predictions_numpy = future_predictions.numpy()

    # Desnormalizar las predicciones
    y_pred_denormalized = scaler.inverse_transform(y_pred_numpy)
    future_predictions_denormalized = scaler.inverse_transform(future_predictions_numpy)

    # Imprimir las predicciones desnormalizadas
    #print("Predicciones desnormalizadas para datos de prueba:")
    #print(y_pred_denormalized)

    print(f"\nPredicciones para los próximos 5 años de la región {num}:()")
    print(future_predictions_denormalized)

    # Convertir las predicciones a DataFrame
    predictions_df = pd.DataFrame(future_predictions_denormalized, columns=y_columns)

    # Guardar el DataFrame en un nuevo archivo CSV
    predictions_df.to_csv(f'predictions_region_{num}.csv', index=False)



    return predictions_df

PredictionsRegion1 =Predictions(dataRegion1,1)
PredictionsRegion2 =Predictions(dataRegion2,2)






Predicciones para los próximos 5 años de la región 1:()
[[-211.94383 8092.4624  6878.2812 ]
 [4347.184   5195.411   6400.7314 ]
 [6365.495   6959.3394  4667.5527 ]
 [-338.67892 4103.164   9410.094  ]
 [7474.0586  7912.738   3699.577  ]]

Predicciones para los próximos 5 años de la región 2:()
[[ 1069.283   2915.1814 -5260.1235]
 [ 2620.4607  4465.4873  -758.0629]
 [ 3436.833   4964.458  16529.14  ]
 [ 2835.4114  4537.785   5638.5347]
 [ 2761.5986  4469.125  12834.847 ]]


Descargar si se desea, las predicciones de ventas de los próximos 5 años para cada región.

In [ ]:
from google.colab import files

In [95]:
# Descargar las nuevas predicciones [opcional]
files.download(f'predictions_region_1.csv')
files.download(f'predictions_region_2.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>