<a href="https://colab.research.google.com/github/Tatoloops/PublicRepository/blob/PyNotebook/Python/Notebooks/Solemne_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solemne III

* Integrantes:  
> Tomás Castillo Á  
> Carlos Campos  
> Sebastián Gonzáles

##Procesamiento de Datos:

el conjunto de datos seleccionado está relacionado con el gasto anual de clientes en diferentes categorías de productos.

In [52]:
from google.colab import files

dataUpload = files.upload()

for fn in dataUpload.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(dataUpload[fn])))

Saving WholesaleCustomersData.xlsx to WholesaleCustomersData (1).xlsx
User uploaded file "WholesaleCustomersData (1).xlsx" with length 23595 bytes


In [53]:
import pandas as pd

dataFrame = pd.read_excel(next(iter(dataUpload.keys())))

Dentro del Dataframe hay información correspondiente a 3 regiones y 2 canales, se procederá a:
* Eliminar toda la información del canal 2.
* Eliminar toda la información de la región 3.
* Eliminar la columna "Channel" correspondiente a los canales (ya que toda la información restante pertenecerá al canal 1)  

Con esto sólo existirán los gastos anuales correspondientes a las categorías de productos para las regiones 1 y 2 sobre el mismo canal.

In [61]:
def delete_column(dataframe, column_name):
    if column_name in dataframe.columns:
        dataframe = dataframe.drop(column_name, axis=1)
        print(f"Column '{column_name}' deleted successfully.")
    else:
        print(f"Column '{column_name}' not found in the DataFrame.")

    return dataframe

def delete_rows(dataframe,name,value):
    if name in dataframe.columns:
        rows_to_delete = dataframe[dataframe[name] == value].index
        dataframe = dataframe.drop(index=rows_to_delete)
        print(f"Rows with '{name}' value equal to {value} deleted successfully.")
    else:
        print(f"Column '{name}' not found in the DataFrame.")

    return dataframe

dataFrame = delete_rows(dataFrame,"Channel",2)
dataFrame = delete_rows(dataFrame,"Region",3)
dataFrame = delete_column(dataFrame,"Channel")
dataFrame = delete_column(dataFrame,"Fresh")
dataFrame = delete_column(dataFrame,"Detergents_Paper")
dataFrame = delete_column(dataFrame,"Delicassen")

Column 'Channel' not found in the DataFrame.
Rows with 'Region' value equal to 3 deleted successfully.
Column 'Channel' not found in the DataFrame.
Column 'Fresh' deleted successfully.
Column 'Detergents_Paper' deleted successfully.
Column 'Delicassen' deleted successfully.


Agregamos una columna nueva a nuestro dataFrame llamada "year", la cual asignará un año a cada fila de nuestro dataset. Este proceso se realizará por cada región de nuestro estudio (1 y 2)

In [62]:

# Assuming your DataFrame is named dataFrame

# Create counters for each region
yearRegion1 = 1
yearRegion2 = 1

# Create an empty list to store the year values
years = []

# Loop through each row in the DataFrame
for index, row in dataFrame.iterrows():
    # Check the region of the current row
    if row['Region'] == 1:
        # Assign the year value based on the region counter
        years.append(yearRegion1)
        # Increment the counter for Region 1
        yearRegion1 += 1
    elif row['Region'] == 2:
        # Assign the year value based on the region counter
        years.append(yearRegion2)
        # Increment the counter for Region 2
        yearRegion2 += 1

# Add the "year" column to the DataFrame
dataFrame['year'] = years

# Display the updated DataFrame
print(dataFrame)


     Region   Milk  Grocery  Frozen  year
196       1   7209     4897   18711     1
198       1   2154     6824    3527     2
199       1   2280     2112     520     3
202       1  11487     9490    5065     4
203       1    685     2216     469     5
..      ...    ...      ...     ...   ...
332       2   3216     1447    2208    24
336       2   1511     1330     650    25
337       2   1347     2611    8170    26
338       2    333     7021   15601    27
339       2   1188     5332    9584    28

[87 rows x 5 columns]


In [66]:
def delete_column(dataframe, column_name):
    if column_name in dataframe.columns:
        dataframe = dataframe.drop(column_name, axis=1)
        print(f"Column '{column_name}' deleted successfully.")
    else:
        print(f"Column '{column_name}' not found in the DataFrame.")

    return dataframe

# Create two separate DataFrames based on the region
dataRegion1 = dataFrame[dataFrame['Region'] == 1]
dataRegion2 = dataFrame[dataFrame['Region'] == 2]

dataRegion1= delete_column(dataRegion1, "Region")
dataRegion2= delete_column(dataRegion2, "Region")
# Display the two DataFrames
print("Data for Region 1:")
print(dataRegion1)

print("\nData for Region 2:")
print(dataRegion2)

Column 'Region' deleted successfully.
Column 'Region' deleted successfully.
Data for Region 1:
      Milk  Grocery  Frozen  year
196   7209     4897   18711     1
198   2154     6824    3527     2
199   2280     2112     520     3
202  11487     9490    5065     4
203    685     2216     469     5
204    891     5226    1383     6
206    780      950     878     7
208   3748     5838    1859     8
210   1895     1393    1801     9
212   1012     2062    1291    10
213   6602     6861    1329    11
215  10765    15538    1374    12
217   1475     2046    2532    13
219    367     1390    2306    14
220    899     1382    1765    15
221   7503    10646      91    16
222   1115     2856    7496    17
224    659     1499     784    18
225   3243     4157     660    19
227   2204     1563    2286    20
228    577      572     950    21
229   2746     2501    6845    22
231  10678     3828    1439    23
232   1780     3838     638    24
233   4984     3316     937    25
234   2703     3833  

Para descargar los nuevos conjuntos de datos

In [67]:
dataRegion1.to_csv('dataRegion1.csv', index=False)
files.download('dataRegion1.csv')

dataRegion2.to_csv('dataRegion2.csv', index=False)
files.download('dataRegion2.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## Entrenando modelo para futuras predicciones:

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Entrenamos nuestra máquina con los datos proporcionados.

In [79]:
# X serán las características de entrada (region, categorías de productos), y será el gasto anual.
X = dataRegion1[['Milk', 'Frozen', 'Grocery']]
y_columns = ['Milk', 'Frozen', 'Grocery']  # Cambiar 'Milk', 'Frozen', 'Grocery' según tus necesidades

# Normalizar los datos
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

# Convertir datos a tensores de PyTorch
X_tensor = torch.tensor(X_normalized, dtype=torch.float32)
y_tensor = torch.tensor(dataRegion1[y_columns].values, dtype=torch.float32)

# División de datos (puedes adaptarlo según tus necesidades)
X_train_tensor, X_test_tensor, y_train_tensor, y_test_tensor = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=42)

# Definir la arquitectura de la red neuronal
class ExpenditurePredictionModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(ExpenditurePredictionModel, self).__init__()
        self.fc = nn.Linear(input_size, output_size)

    def forward(self, x):
        return self.fc(x)

# Definir la función de pérdida y el optimizador
criterion = nn.MSELoss()

# Entrenamiento del modelo
model = ExpenditurePredictionModel(X_train_tensor.shape[1], len(y_columns))
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 50
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

# Evaluación del modelo en datos de prueba
model.eval()
with torch.no_grad():
    y_pred_tensor = model(X_test_tensor)

# Predicción para las siguientes 5 filas
with torch.no_grad():
    future_data = X_test_tensor[:5]
    future_predictions = model(future_data)

# Convertir los tensores de PyTorch a numpy arrays
y_pred_numpy = y_pred_tensor.numpy()
future_predictions_numpy = future_predictions.numpy()

# Imprimir las predicciones
print("Predicciones para datos de prueba:")
print(y_pred_numpy)

print("\nPredicciones para las siguientes 5 filas:")
print(future_predictions_numpy)

# Desnormalizar las predicciones
y_pred_denormalized = scaler.inverse_transform(y_pred_numpy)
future_predictions_denormalized = scaler.inverse_transform(future_predictions_numpy)

# Imprimir las predicciones desnormalizadas
print("Predicciones desnormalizadas para datos de prueba:")
print(y_pred_denormalized)

print("\nPredicciones desnormalizadas para las siguientes 5 filas:")
print(future_predictions_denormalized)




Predicciones para datos de prueba:
[[ 2.73504257e+00  1.35913837e+00  1.07082725e+00]
 [ 3.03893924e-01  8.79622996e-03 -2.78507262e-01]
 [ 1.07823044e-01 -3.22485954e-01 -3.45928632e-02]
 [ 4.10275280e-01 -3.61101091e-01 -5.45934081e-01]
 [ 5.51346242e-02 -4.37272102e-01  1.21041417e-01]
 [ 1.12241673e+00  2.22820714e-01  3.02341938e+00]
 [ 1.10977620e-01 -8.59350860e-01 -9.16533917e-02]
 [ 6.71165466e-01 -1.12931728e-02 -6.07222654e-02]
 [ 9.25955296e-01 -1.57405451e-01  1.12632915e-01]
 [ 4.22695369e-01 -3.40740085e-01 -3.76866013e-01]
 [ 2.24944949e-03 -8.57240021e-01 -9.80802029e-02]
 [ 6.26910686e-01  1.01936474e-01  1.26930666e+00]]

Predicciones para las siguientes 5 filas:
[[ 2.7350426   1.3591384   1.0708272 ]
 [ 0.30389392  0.00879623 -0.27850726]
 [ 0.10782304 -0.32248595 -0.03459286]
 [ 0.41027528 -0.3611011  -0.5459341 ]
 [ 0.05513462 -0.4372721   0.12104142]]
Predicciones desnormalizadas para datos de prueba:
[[15526.241    7542.585    7879.7783 ]
 [ 5165.32     3155.897